skip_branch_with_pr: true

environment:
  matrix:  
    - PYTHON: C:\Python35
      TOX_ENV: py35

    - PYTHON: C:\Python36
      TOX_ENV: py36

install:
  - "%PYTHON%/python.exe -m pip install -U pip tox wheel"

build: false  # Not a C# project

test_script:
   - "%PYTHON%/Scripts/tox -e %TOX_ENV%"
